old-dtb := $(dtb-y)
old-dtbo := $(dtbo-y)
dtb-y :=
dtbo-y :=
makefile-path := platform/t19x/jakku/kernel-dts

dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-kexec.dtb
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-hdr40.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-adafruit-sph0645lm4h.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-adafruit-uda1334a.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-fe-pi-audio.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-respeaker-4-mic-array.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-respeaker-4-mic-lin-array.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-m2ke.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-camera-imx477-imx219.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-camera-imx477-dual.dtbo
dtbo-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-p3668-all-p3509-0000-camera-imx219-dual.dtbo

dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-RPI-IMX219-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-ECON-AR0521-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-ARDU-IMX477-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-BASLER-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-ECON-IMX415-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-ECON-AR0234-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX003-ECON-AR0330-2CAM.dtb


dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-RPI-IMX219-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-ARDU-IMX477-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-ECON-AR0521-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-BASLER-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-ECON-IMX415-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-ECON-AR0234-2CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX004-ECON-AR0330-2CAM.dtb

dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006-ECON-AR0330-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006-ECON-AR0230-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006-ECON-AR0233-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006-LI-IMX390-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX006-LI-IMX304-2CAM.dtb

dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX264-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX290-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX290-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX296-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX297-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX334-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX335-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX335-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX412-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX412-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX415-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX415-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX477-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX477-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX565-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX530-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX565-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX577-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX577-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX585-3CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX585-4CAM.dtb

dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX464-4CAM.dtb
dtb-$(CONFIG_ARCH_TEGRA_19x_SOC) += tegra194-xavier-nx-cti-NGX007-FSM-IMX464-3CAM.dtb

ifneq ($(dtb-y),)
dtb-y := $(addprefix $(makefile-path)/,$(dtb-y))
endif
ifneq ($(dtbo-y),)
dtbo-y := $(addprefix $(makefile-path)/,$(dtbo-y))
endif

dtb-y += $(old-dtb)
dtbo-y += $(old-dtbo)
