tis_sensor_common-y = tis_sensor_shared.o tis_sensor_parts.o tis_sensor_debug.o tis_sensor_regmap.o tis_sensor_ctrl.o tis_tegracam_v4l2.o tis_sensor_connection.o tis_sensor_connection_fpdlink.o
obj-$(CONFIG_VIDEO_TISSENSOR)	+= tis_imx390.o
obj-$(CONFIG_VIDEO_TISSENSOR) += tis_imx290.o
obj-$(CONFIG_VIDEO_TISSENSOR) += tis_imx415.o
obj-$(CONFIG_VIDEO_TISSENSOR) += tis_sensor_common.o
