obj-$(CONFIG_I2C_TISFPDLINK)	+= tis-fpdlink.o
obj-$(CONFIG_I2C_TISINTERPOSER)    += tis_interposer.o
obj-$(CONFIG_I2C_TISEDGECAMCTRL)   += tis-edgecam-ctrl.o
obj-$(CONFIG_I2C_TISSI5356)	+= tis-si5356.o
